spring.application.name=TestSecurity
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Play
jwt.secret.key=V2hhdEV2ZXJZb3VEb1JlbWVtYmVyVG9LZWVwSXRTZWNyZXRTYWZlQW5kTG9uZ0Vub3VnaF9TdW5pbF9KV1RfSFM1MTJfS2V5XzIwMjY=